apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc
  namespace: lab16-sehs
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: crc-csi-hostpath-provisioner
  resources:
    requests:
      storage: 5Gi
